### ISSUE TITLE
Add custom PHP modules to a site

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/feature-requests#67] opened 2018-12-14 11:54 UTC
Currently, there's no possible way to add a custom PHP module while having the assurity that it will be persisted and not deleted. As this feature is frequently needed, we should add some provision to it.

**Comment by mrrobot47** [comment] 2018-12-14 12:37
Closing as duplicate of https://github.com/EasyEngine/easyengine/issues/1313

**Closed as completed by mrrobot47** 2018-12-14 12:37 UTC
