### ISSUE TITLE
Logrotate: Nginx / PHP Logs

### ISSUE THREAD

**Issue by scysys** [EasyEngine/feature-requests#81] opened 2019-07-25 08:43 UTC
Does not find anything to this. I know how to enable myself the needed function. But im wonder that Easyengine 4 have nothing to this on board?

On one Site I deleted for 5 Minutes PHP error and access logs with a few GB.

**Comment by kirtangajjar** [comment] 2020-12-23 12:27
Duplicate of - https://github.com/EasyEngine/feature-requests/issues/73

**Closed as completed by kirtangajjar** 2020-12-23 12:27 UTC
